name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test bat_power
      run: pytest -m bat_power
    - name: Test signal_strength
      run: pytest -m signal_strength
    - name: Test vehicles
      run: pytest -m vehicles
    - name: Test joker_info
      run: pytest -m joker_info
    
